### ISSUE TITLE
Genshin Impact

### ISSUE THREAD

**Issue by wzc2904274** [UuuNyaa/blender_mmd_assets#197]
## thumbnail_url
![thumbnail_url](https://bkimg.cdn.bcebos.com/pic/fc1f4134970a304e251f0138d885b086c9177e3ef696?x-bce-process=image/resize,m_lfit,w_536,limit_1/format,f_jpg)

## source_url
http://tstorage.info/files/1/k06ntv8u7ikm8d/Tda%20Lumine%20Natsuyi_edit%20v0.9.rar

## download_action
```python
get('http://tstorage.info/files/1/k06ntv8u7ikm8d/Tda%20Lumine%20Natsuyi_edit%20v0.9.rar')
```

## import_action
```python
unzip(encoding='cp932'); import_pmx('path/ying.pmx',scale=0.08)
```

## aliases
| en | ying |
|--|--|
| ja | ying |

**Comment by UuuNyaa** [comment]
@wzc2904274 Thanks for adding the asset.

If you want to download from tstorage, write download_action as follows:
```python
tstorage('http://tstorage.info/xxxxxxxx')
```

see: https://github.com/UuuNyaa/blender_mmd_assets/issues/177

**Comment by LauraKami** [comment]
Hi @UuuNyaa the link for asset of Traveler female don't work anymore.
mi ho yo prohibits the storage of models (to be able to modify them in case of censorship).
You can use my repository to find the 59 Genshin Impact models (these are links to the official versions).
https://mikumikudance.fr/genshin_impact/
have fun
Laurakami

**Comment by UuuNyaa** [comment]
@LauraKami Thanks for the report 😃
I will update the link.

**Comment by UuuNyaa** [comment]
@LauraKami I have verified that the following 2 assets are available for download.
* https://github.com/UuuNyaa/blender_mmd_assets/issues/1
* https://github.com/UuuNyaa/blender_mmd_assets/issues/2

This issue is closed because it is broken.
