### ISSUE TITLE
Eula

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_assets#91]
## thumbnail_url
![thumbnail_url](https://user-images.githubusercontent.com/44924233/120057427-de6c0c00-c07d-11eb-81c7-9fe7a363f155.png)

## source_url
https://ecchi.iwara.tv/images/%E3%80%90%E5%8E%9F%E7%A5%9E%E3%80%91%E4%BC%98%E8%8F%88r18%E6%94%B9%E6%A8%A1%E9%85%8D%E5%B8%83-genshin-impact-eula-nsfw-edited-model-dl

## download_action
```python
gdrive('https://drive.google.com/file/d/1O0rZKgeZ-qsN70zQAfG2BK7EsOfXs_g6/view?usp=sharing')
```

## import_action
```python
un7zip(); import_pmx('Eula_R18_MDJSN_edit_v1.0/Eula_R18_v1.0.pmx',scale=0.08)
```

## aliases
| en | Eula |
|--|--|
| ja | エウルア |

**Comment by RAZUMNO** [comment]
Version 1.1 available [https://drive.google.com/file/d/1e1OgJq8fjkLO7TnPCKCw2YD2y849_sQH/view?usp=sharing](url)

**Comment by listelin** [comment]
Thank you.
I have created a new issue #171
